// GetPolicy internal API (docs §6.7). gRPC because it sits on the hot
// path: moderation-service calls it on every local-cache miss. A negative
// result (found=false) is a valid, cacheable answer.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: policy.proto

package policyapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SpamMode int32

const (
	SpamMode_SPAM_MODE_UNSPECIFIED SpamMode = 0
	SpamMode_SPAM_MODE_NONE        SpamMode = 1
	SpamMode_SPAM_MODE_IDENTICAL   SpamMode = 2
	SpamMode_SPAM_MODE_SEMANTIC    SpamMode = 3
)

// Enum value maps for SpamMode.
var (
	SpamMode_name = map[int32]string{
		0: "SPAM_MODE_UNSPECIFIED",
		1: "SPAM_MODE_NONE",
		2: "SPAM_MODE_IDENTICAL",
		3: "SPAM_MODE_SEMANTIC",
	}
	SpamMode_value = map[string]int32{
		"SPAM_MODE_UNSPECIFIED": 0,
		"SPAM_MODE_NONE":        1,
		"SPAM_MODE_IDENTICAL":   2,
		"SPAM_MODE_SEMANTIC":    3,
	}
)

func (x SpamMode) Enum() *SpamMode {
	p := new(SpamMode)
	*p = x
	return p
}

func (x SpamMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SpamMode) Descriptor() protoreflect.EnumDescriptor {
	return file_policy_proto_enumTypes[0].Descriptor()
}

func (SpamMode) Type() protoreflect.EnumType {
	return &file_policy_proto_enumTypes[0]
}

func (x SpamMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SpamMode.Descriptor instead.
func (SpamMode) EnumDescriptor() ([]byte, []int) {
	return file_policy_proto_rawDescGZIP(), []int{0}
}

type RestrictedContentAction int32

const (
	RestrictedContentAction_RESTRICTED_CONTENT_ACTION_UNSPECIFIED RestrictedContentAction = 0
	RestrictedContentAction_RESTRICTED_CONTENT_ACTION_AUTO        RestrictedContentAction = 1
	RestrictedContentAction_RESTRICTED_CONTENT_ACTION_REVIEW      RestrictedContentAction = 2
)

// Enum value maps for RestrictedContentAction.
var (
	RestrictedContentAction_name = map[int32]string{
		0: "RESTRICTED_CONTENT_ACTION_UNSPECIFIED",
		1: "RESTRICTED_CONTENT_ACTION_AUTO",
		2: "RESTRICTED_CONTENT_ACTION_REVIEW",
	}
	RestrictedContentAction_value = map[string]int32{
		"RESTRICTED_CONTENT_ACTION_UNSPECIFIED": 0,
		"RESTRICTED_CONTENT_ACTION_AUTO":        1,
		"RESTRICTED_CONTENT_ACTION_REVIEW":      2,
	}
)

func (x RestrictedContentAction) Enum() *RestrictedContentAction {
	p := new(RestrictedContentAction)
	*p = x
	return p
}

func (x RestrictedContentAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RestrictedContentAction) Descriptor() protoreflect.EnumDescriptor {
	return file_policy_proto_enumTypes[1].Descriptor()
}

func (RestrictedContentAction) Type() protoreflect.EnumType {
	return &file_policy_proto_enumTypes[1]
}

func (x RestrictedContentAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RestrictedContentAction.Descriptor instead.
func (RestrictedContentAction) EnumDescriptor() ([]byte, []int) {
	return file_policy_proto_rawDescGZIP(), []int{1}
}

type GetPolicyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CreatorId     string                 `protobuf:"bytes,1,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	Platform      string                 `protobuf:"bytes,2,opt,name=platform,proto3" json:"platform,omitempty"`
	ContentId     string                 `protobuf:"bytes,3,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPolicyRequest) Reset() {
	*x = GetPolicyRequest{}
	mi := &file_policy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPolicyRequest) ProtoMessage() {}

func (x *GetPolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_policy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPolicyRequest.ProtoReflect.Descriptor instead.
func (*GetPolicyRequest) Descriptor() ([]byte, []int) {
	return file_policy_proto_rawDescGZIP(), []int{0}
}

func (x *GetPolicyRequest) GetCreatorId() string {
	if x != nil {
		return x.CreatorId
	}
	return ""
}

func (x *GetPolicyRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *GetPolicyRequest) GetContentId() string {
	if x != nil {
		return x.ContentId
	}
	return ""
}

type GetPolicyResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Found bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	// Set only when found is true.
	Policy        *ResolvedPolicy `protobuf:"bytes,2,opt,name=policy,proto3" json:"policy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPolicyResponse) Reset() {
	*x = GetPolicyResponse{}
	mi := &file_policy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPolicyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPolicyResponse) ProtoMessage() {}

func (x *GetPolicyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_policy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPolicyResponse.ProtoReflect.Descriptor instead.
func (*GetPolicyResponse) Descriptor() ([]byte, []int) {
	return file_policy_proto_rawDescGZIP(), []int{1}
}

func (x *GetPolicyResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *GetPolicyResponse) GetPolicy() *ResolvedPolicy {
	if x != nil {
		return x.Policy
	}
	return nil
}

// One restricted_content rubric entry (§6.3): title and description are
// what the LLM judges against; examples are few-shot anchors.
type RestrictedContentEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Examples      []string               `protobuf:"bytes,3,rep,name=examples,proto3" json:"examples,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestrictedContentEntry) Reset() {
	*x = RestrictedContentEntry{}
	mi := &file_policy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestrictedContentEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestrictedContentEntry) ProtoMessage() {}

func (x *RestrictedContentEntry) ProtoReflect() protoreflect.Message {
	mi := &file_policy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestrictedContentEntry.ProtoReflect.Descriptor instead.
func (*RestrictedContentEntry) Descriptor() ([]byte, []int) {
	return file_policy_proto_rawDescGZIP(), []int{2}
}

func (x *RestrictedContentEntry) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *RestrictedContentEntry) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RestrictedContentEntry) GetExamples() []string {
	if x != nil {
		return x.Examples
	}
	return nil
}

type ResolvedPolicy struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// policy_id and resolved_at ride along so flagged events can record
	// which policy produced the verdict.
	PolicyId   string                 `protobuf:"bytes,1,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	ResolvedAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=resolved_at,json=resolvedAt,proto3" json:"resolved_at,omitempty"`
	// Rate limit: both set or both absent (absent = no rate limiting).
	RateLimitMessages       *int32                    `protobuf:"varint,3,opt,name=rate_limit_messages,json=rateLimitMessages,proto3,oneof" json:"rate_limit_messages,omitempty"`
	RateLimitSeconds        *int32                    `protobuf:"varint,4,opt,name=rate_limit_seconds,json=rateLimitSeconds,proto3,oneof" json:"rate_limit_seconds,omitempty"`
	Spam                    SpamMode                  `protobuf:"varint,5,opt,name=spam,proto3,enum=dabet.policy.v1.SpamMode" json:"spam,omitempty"`
	RestrictedWords         []string                  `protobuf:"bytes,6,rep,name=restricted_words,json=restrictedWords,proto3" json:"restricted_words,omitempty"`
	RestrictedContent       []*RestrictedContentEntry `protobuf:"bytes,7,rep,name=restricted_content,json=restrictedContent,proto3" json:"restricted_content,omitempty"`
	RestrictedContentAction RestrictedContentAction   `protobuf:"varint,8,opt,name=restricted_content_action,json=restrictedContentAction,proto3,enum=dabet.policy.v1.RestrictedContentAction" json:"restricted_content_action,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ResolvedPolicy) Reset() {
	*x = ResolvedPolicy{}
	mi := &file_policy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolvedPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolvedPolicy) ProtoMessage() {}

func (x *ResolvedPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_policy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolvedPolicy.ProtoReflect.Descriptor instead.
func (*ResolvedPolicy) Descriptor() ([]byte, []int) {
	return file_policy_proto_rawDescGZIP(), []int{3}
}

func (x *ResolvedPolicy) GetPolicyId() string {
	if x != nil {
		return x.PolicyId
	}
	return ""
}

func (x *ResolvedPolicy) GetResolvedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ResolvedAt
	}
	return nil
}

func (x *ResolvedPolicy) GetRateLimitMessages() int32 {
	if x != nil && x.RateLimitMessages != nil {
		return *x.RateLimitMessages
	}
	return 0
}

func (x *ResolvedPolicy) GetRateLimitSeconds() int32 {
	if x != nil && x.RateLimitSeconds != nil {
		return *x.RateLimitSeconds
	}
	return 0
}

func (x *ResolvedPolicy) GetSpam() SpamMode {
	if x != nil {
		return x.Spam
	}
	return SpamMode_SPAM_MODE_UNSPECIFIED
}

func (x *ResolvedPolicy) GetRestrictedWords() []string {
	if x != nil {
		return x.RestrictedWords
	}
	return nil
}

func (x *ResolvedPolicy) GetRestrictedContent() []*RestrictedContentEntry {
	if x != nil {
		return x.RestrictedContent
	}
	return nil
}

func (x *ResolvedPolicy) GetRestrictedContentAction() RestrictedContentAction {
	if x != nil {
		return x.RestrictedContentAction
	}
	return RestrictedContentAction_RESTRICTED_CONTENT_ACTION_UNSPECIFIED
}

var File_policy_proto protoreflect.FileDescriptor

const file_policy_proto_rawDesc = "" +
	"\n" +
	"\fpolicy.proto\x12\x0fdabet.policy.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"l\n" +
	"\x10GetPolicyRequest\x12\x1d\n" +
	"\n" +
	"creator_id\x18\x01 \x01(\tR\tcreatorId\x12\x1a\n" +
	"\bplatform\x18\x02 \x01(\tR\bplatform\x12\x1d\n" +
	"\n" +
	"content_id\x18\x03 \x01(\tR\tcontentId\"b\n" +
	"\x11GetPolicyResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x127\n" +
	"\x06policy\x18\x02 \x01(\v2\x1f.dabet.policy.v1.ResolvedPolicyR\x06policy\"l\n" +
	"\x16RestrictedContentEntry\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1a\n" +
	"\bexamples\x18\x03 \x03(\tR\bexamples\"\x99\x04\n" +
	"\x0eResolvedPolicy\x12\x1b\n" +
	"\tpolicy_id\x18\x01 \x01(\tR\bpolicyId\x12;\n" +
	"\vresolved_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"resolvedAt\x123\n" +
	"\x13rate_limit_messages\x18\x03 \x01(\x05H\x00R\x11rateLimitMessages\x88\x01\x01\x121\n" +
	"\x12rate_limit_seconds\x18\x04 \x01(\x05H\x01R\x10rateLimitSeconds\x88\x01\x01\x12-\n" +
	"\x04spam\x18\x05 \x01(\x0e2\x19.dabet.policy.v1.SpamModeR\x04spam\x12)\n" +
	"\x10restricted_words\x18\x06 \x03(\tR\x0frestrictedWords\x12V\n" +
	"\x12restricted_content\x18\a \x03(\v2'.dabet.policy.v1.RestrictedContentEntryR\x11restrictedContent\x12d\n" +
	"\x19restricted_content_action\x18\b \x01(\x0e2(.dabet.policy.v1.RestrictedContentActionR\x17restrictedContentActionB\x16\n" +
	"\x14_rate_limit_messagesB\x15\n" +
	"\x13_rate_limit_seconds*j\n" +
	"\bSpamMode\x12\x19\n" +
	"\x15SPAM_MODE_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eSPAM_MODE_NONE\x10\x01\x12\x17\n" +
	"\x13SPAM_MODE_IDENTICAL\x10\x02\x12\x16\n" +
	"\x12SPAM_MODE_SEMANTIC\x10\x03*\x8e\x01\n" +
	"\x17RestrictedContentAction\x12)\n" +
	"%RESTRICTED_CONTENT_ACTION_UNSPECIFIED\x10\x00\x12\"\n" +
	"\x1eRESTRICTED_CONTENT_ACTION_AUTO\x10\x01\x12$\n" +
	" RESTRICTED_CONTENT_ACTION_REVIEW\x10\x022c\n" +
	"\rPolicyService\x12R\n" +
	"\tGetPolicy\x12!.dabet.policy.v1.GetPolicyRequest\x1a\".dabet.policy.v1.GetPolicyResponseB\x15Z\x13dabet/pkg/policyapib\x06proto3"

var (
	file_policy_proto_rawDescOnce sync.Once
	file_policy_proto_rawDescData []byte
)

func file_policy_proto_rawDescGZIP() []byte {
	file_policy_proto_rawDescOnce.Do(func() {
		file_policy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_policy_proto_rawDesc), len(file_policy_proto_rawDesc)))
	})
	return file_policy_proto_rawDescData
}

var file_policy_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_policy_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_policy_proto_goTypes = []any{
	(SpamMode)(0),                  // 0: dabet.policy.v1.SpamMode
	(RestrictedContentAction)(0),   // 1: dabet.policy.v1.RestrictedContentAction
	(*GetPolicyRequest)(nil),       // 2: dabet.policy.v1.GetPolicyRequest
	(*GetPolicyResponse)(nil),      // 3: dabet.policy.v1.GetPolicyResponse
	(*RestrictedContentEntry)(nil), // 4: dabet.policy.v1.RestrictedContentEntry
	(*ResolvedPolicy)(nil),         // 5: dabet.policy.v1.ResolvedPolicy
	(*timestamppb.Timestamp)(nil),  // 6: google.protobuf.Timestamp
}
var file_policy_proto_depIdxs = []int32{
	5, // 0: dabet.policy.v1.GetPolicyResponse.policy:type_name -> dabet.policy.v1.ResolvedPolicy
	6, // 1: dabet.policy.v1.ResolvedPolicy.resolved_at:type_name -> google.protobuf.Timestamp
	0, // 2: dabet.policy.v1.ResolvedPolicy.spam:type_name -> dabet.policy.v1.SpamMode
	4, // 3: dabet.policy.v1.ResolvedPolicy.restricted_content:type_name -> dabet.policy.v1.RestrictedContentEntry
	1, // 4: dabet.policy.v1.ResolvedPolicy.restricted_content_action:type_name -> dabet.policy.v1.RestrictedContentAction
	2, // 5: dabet.policy.v1.PolicyService.GetPolicy:input_type -> dabet.policy.v1.GetPolicyRequest
	3, // 6: dabet.policy.v1.PolicyService.GetPolicy:output_type -> dabet.policy.v1.GetPolicyResponse
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_policy_proto_init() }
func file_policy_proto_init() {
	if File_policy_proto != nil {
		return
	}
	file_policy_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_policy_proto_rawDesc), len(file_policy_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_policy_proto_goTypes,
		DependencyIndexes: file_policy_proto_depIdxs,
		EnumInfos:         file_policy_proto_enumTypes,
		MessageInfos:      file_policy_proto_msgTypes,
	}.Build()
	File_policy_proto = out.File
	file_policy_proto_goTypes = nil
	file_policy_proto_depIdxs = nil
}
